gettext-rs/gettext-rs

- src/lib.rs
* Added docs for `LocaleCategory` enum (taken from `man locale`)
* Ran `rustfmt` on the code
* Changed function names and enum variants to Rust conventions (snake case names).
Code compiles w/o warnings now (yay!)
If you don't like the changes made by `rustfmt`, I can revert it back =) 
You can update the docs at gh-pages.
> Update docs, follow rust convention, run rustfmt

- README.md
- gettext-sys/build.rs
- systest/build.rs
Add support for building on Windows + GNU. At the moment, this has been tested on a fresh install of MSYS2 in both system's `gettext` and internal static builds variants.
On AppVeyor, [internal static build fails](https://ci.appveyor.com/project/fengalin/media-toc/build/1.0.335/job/ax0b0ml4an0y1l6i) due to `make` not being able to find `libgnuintl.h` and `libintl.h`. I don't know how to solve this, so I recommend using system's `gettext` on this environment. Due to the long build time with the internal static `gettext` on Windows, it seems preferable anyway.
> Build on Windows + GNU (e.g. MSYS2)

- Cargo.toml
- README.md
- gettext-sys/Cargo.toml
- gettext-sys/build.rs
Add the `gettext-system` feature in order to activate building against the
system's `gettext` without the need to set an environment variable.
> Add a `gettext-system` feature

- Cargo.toml
- README.md
- src/lib.rs
- src/text_domain.rs
Use current locale and find the path to bind by searching translations
in the system data paths and optionally in user specified paths.
Just a few notes:
- I took the liberty to use `LocaleCategory::LcMessages` as the default.
Of course, i can change this if you prefer using `LocaleCategory::LcAll`.
- On Windows & MacOS, there might be specific ways to get the system
data dirs, but I don't know about these.
> Add TextDomain builder to initialize locale and textdomain

- README.md
- src/lib.rs
- src/text_domain.rs
Sorry for the noise... I just realized it made more sense using `unwrap` in the examples.
> TextDomain: use `unwrap` instead of `ok` in examples

- README.md
- src/lib.rs
This patch adds two new functions to be able to use context in
translations, the pgettext and the npgettext.
pgettext and npgettext are implemented with C macros in the gettext
library so I've to implement in rust code here.
This implementation is based on the django version:
https://github.com/django/django/blob/master/django/utils/translation/trans_real.py#L301
This will fix: #10
> pgettext function added to translate with context

- gettext-sys/build.rs
Musl's gettext support is in somewhat good shape now, so we can use it instead
of GNU gettext
fixes #14
> Use musl's gettext support with GETTEXT_SYSTEM

- src/lib.rs
I'm facing an issue because I'm storing the category in a struct but then when I want to pass it to the function I cannot because it's moved by default and I cannot clone it either.
Would it be okay for you to make derive from Clone and from Copy?
> derive Clone and Copy for LocaleCategory

- src/lib.rs
- src/macros.rs
The macros behave the same as format! does, so it can be used like this:
gettext!("Hello, {user}!", user = x);
I've only tested `gettext!`, since that's what I use in my codebase, but other stuff should work too - I'll look into that. Also, I'll still need to make docs for this.
fixes #18
> Add macros for functions so users can use placeholders

- .travis.yml
Two Travis jobs currently fail because their output exceeds log length limit:
- https://travis-ci.org/github/Koka/gettext-rs/jobs/653263406#L24922
- https://travis-ci.org/github/Koka/gettext-rs/jobs/653263407#L24908
By `diff`ing the output with the last passing job, https://travis-ci.org/github/Koka/gettext-rs/jobs/417123508, I found that Cargo now prints out a progress bar. Travis stores each update of the progress bar as a separate line in the log, which eventually reaches the limit.
This is a known problem (https://github.com/rust-lang/cargo/issues/5721), and I applied the suggested solution, which is: set `TERM` environment variable to `dumb` to disable the progress bar. I believe this won't affect the usefulness of the output.
> Travis: avoid exceeding log length limit

- gettext-sys/build.rs
I was having trouble reproducing a build on GNOME's Gitlab instance. The reason for the failed builds was because I was using the latest Fedora Docker image, while my computer has the latest Fedora Workstation image. For some reason the Fedora Docker image did not come with some of the basic programs the C gettext code requires to compile. It took me a long time* to sift through the output to figure out the issues were caused by missing CLI programs.
This PR adds a check to determine if the required programs are on the machine, or fails the build with a clean panic message. I checked the added code works on my machine, but I did not check if it'll work on another OS or Github's Actions.
[My Gitlab CI yml file](https://gitlab.gnome.org/dleggo/recipes/-/blob/rust-port/.gitlab-ci.yml) …
> Dependency check to build GNU gettext

- gettext-rs/README.md
- gettext-rs/src/lib.rs
- gettext-rs/src/text_domain.rs
Fixes #35.
In the second commit, e43a2db, I pedalled back on my earlier statement about `Into<String>` (https://github.com/Koka/gettext-rs/issues/36#issuecomment-782714274). As the commit message explains, the situation has changed: previously we didn't care about what's being passed, but now we do, so in order to prevent panics, we have to enforce that inputs are in UTF-8 too.
> Require users to configure gettext for UTF-8

- gettext-rs/src/lib.rs
- gettext-rs/src/macros.rs
Previously we would format the strings and then pass them to gettext. This would
lead to gettext not being able to find the strings in the .po file (since that
contains the unformatted strings).
fixes #18
First shot at this @Minoru , I'll have to test this more at the weekend with actual .po files and stuff
> WIP: macros: only format strings after passing them to gettext

- gettext-rs/src/lib.rs
- gettext-sys/lib.rs
While working on https://github.com/Koka/gettext-rs/issues/12#issuecomment-787205155 I managed to get the crates into a buildable state, and so fixed my erroneous conversions around the `wbindtextdomain` call.
I still have no idea if it actually *works*, because I couldn't link anything and thus couldn't run tests. Come to think of it, our tests don't actually test the behaviour of these calls anyway, so *shrug*. At least the next person who touches this code won't have to start from scratch.
> Fix wbindtextdomain call

- gettext-rs/README.md
- gettext-rs/src/lib.rs
- gettext-rs/src/macros.rs
- gettext-rs/src/text_domain.rs
This PR is kind of in the middle between #35 and #44: textdomain-related functions returned `String`, which wasn't always appropriate, and they also hid the errors in the underlying API. This PR fixes all that.
Most of these changes are breaking.
> Make *textdomain* functions fallible

- gettext-sys/CHANGELOG.md
- gettext-sys/Cargo.toml
- gettext-sys/README.md
- gettext-sys/build.rs
This works around the autotools limitation, which prevented us from
building in directories whose absolute paths have spaces in them.
Fixes #9.
> gettext-sys: build in a temporary directory

- gettext-rs/CHANGELOG.md
- gettext-rs/README.md
- gettext-rs/src/lib.rs
- gettext-rs/src/macros.rs
- gettext-rs/src/text_domain.rs
This makes it easier to use `TextDomain` with the `?` operator.
b3b78ed fixes a little mistake that slipped through in #47: we made the `mod macros` public, but it doesn't make sense since that module only contains macros, which are hoisted to the crate root by `#[macro_export]`.
> impl Error for TextDomainError

- gettext-sys/Cargo.toml
- gettext-sys/build.rs
The `tempfile` crate has a bunch of dependencies through its reliance
on the `Rand` crate, while `temp-dir` only relies on `std`.
Resolves: #67
See also: https://github.com/newsboat/newsboat/issues/1550, https://github.com/newsboat/newsboat/pull/1700
> gettext-sys: replace `tempfile` with `temp-dir`

- gettext-sys/CHANGELOG.md
- gettext-sys/Cargo.toml
- gettext-sys/build.rs
> gettext-sys: specify libdir explicitly, release 0.21.2

- gettext-rs/src/macros.rs
Hi! This time it's nothing radical. These macros have the following improvements:
- Can be used without arguments
- In `dev` build, panics with different messages for situations when there are less/more arguments than format directives
- Can have ~~one~~ `{n}` format directive for including number used as `n` in `ngettext`
Should be tested with both `cargo test` and `cargo test --release`. Tests for situations when there are less/more arguments than format directives do not test if panics happen and in which build profile.
TODO:
> Improved macros

- gettext-sys/build.rs
Otherwise they will be checked also in the cases where
the env variables are provided
> Check dependencies to build the tarball right before building it

- .github/workflows/macos.yml
macOS 10.15 is deprecated: https://github.com/actions/virtual-environments/issues/5583
> CI: migrate to macOS 11

- .github/workflows/linux.yml
- .github/workflows/rustfmt.yml
Ubuntu 18.04 is no longer available with GitHub-hosted runners, so the Linux workflow didn't even run anymore.
> CI: update to Ubuntu 22.04

- .github/workflows/linux.yml
Tests segfault since Rust 1.62.0, so I'm disabling them to make progress on other PRs. See #99.
> CI: disable Musl builds

- .github/workflows/linux.yml
- .github/workflows/macos.yml
MacOS 11 was removed from GitHub hosted runners a few weeks ago. This PR replaces it with the three versions that are available. That includes macOS 14 which runs on Apple Silicon.
> CI: update macOS

- gettext-rs/Cargo.toml
- gettext-rs/tests/integration.rs
- gettext-sys/Cargo.toml
- gettext-sys/build.rs
Resolves https://github.com/Koka/gettext-rs/issues/114
Resolves https://github.com/Koka/gettext-rs/issues/117
Relevant gnulib commit: [0cc39712](https://git.savannah.gnu.org/cgit/gnulib.git/commit/lib/obstack.c?id=0cc39712803ade7b2d4b89c36b143dad72404063)
> running 11 tests
> error: test failed, to rerun pass `-p gettext-rs --test integration`
> 
> Caused by:
>   process didn't exit successfully: `/home/dennis/tmp-projects/gettext-rs/target/debug/deps/integration-7e0d0a9f78988c74` (signal: 6, SIGABRT: process abort signal)
- Turns out this was caused by passing in an invalid value for the `category` argument of `dcgettext()`.
From https://www.gnu.org/software/libc/manual/html_node/Translation-with-gettext.html:
> Normally the available values are LC_CTYPE, LC_COLLATE, LC_MESSAGES, …
> Update to gettext 22.5

- .cirrus.yml
https://www.freebsd.org/news/newsflash/#2024-12-03:1
> CI: bump FreeBSD from 14.1 to 14.2
